[versions]
jsoup = "1.21.2"
kotlinx-serialization-json = "1.9.0"
ktor = "3.2.3"
webidl-util = "0.10.2"
wgpu4k-native = "v25.0.2"
kaml = "0.92.0"
kotlin = "2.3.0"
agp = "8.12.0"
coroutines = "1.10.2"
kotlinpoet = "2.2.0"

# Tests
kotest = "6.0.7"
ksp = "2.3.4"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
webidl-util = { module = "de.fabmax:webidl-util", version.ref = "webidl-util" }
wgpu-specs = { module = "io.ygdrasil:wgpu4k-native-specs-jvm", version.ref = "wgpu4k-native" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

# LLM
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

# Release
zip4j = { module = "net.lingala.zip4j:zip4j", version = "2.11.5" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.12.0" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "2.0.0" }
commons-io = { module = "commons-io:commons-io", version = "2.20.0" }

# Tests
kotest-core = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Tests
kotest = { id = "io.kotest", version.ref = "kotest" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
kotest = ["kotest-core", "kotest-assertions"]